apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: default
spec:
  selector:
    app: flask-api
  type: ClusterIP

  ports:
  - name: flask-api-service
    protocol: TCP
    port: 5000
    targetPort: 5000
